FROM dockcross/linux-x64
MAINTAINER Oliver Dick "oliver.dick@evilstorm.com"

RUN apt-get update && apt-get -y install \
    libx11-dev \
    libopenal-dev \
    freeglut3 \
    freeglut3-dev \
    libglew1.5 \
    libglew1.5-dev \
    libglu1-mesa \
    libglu1-mesa-dev \
    libgl1-mesa-glx \
    libgl1-mesa-dev \
    default-jre
