FROM dockcross/linux-x86
MAINTAINER Oliver Dick "oliver.dick@evilstorm.com"

RUN apt-get update && apt-get -y install \
    libx11-dev:i386 \
    libopenal-dev:i386 \
    freeglut3:i386 \
    freeglut3-dev:i386 \
    libglew1.5:i386 \
    libglew1.5-dev:i386 \
    libglu1-mesa:i386 \
    libglu1-mesa-dev:i386 \
    libgl1-mesa-glx:i386 \
    libgl1-mesa-dev:i386 \
    default-jre
